### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by P110** [TheHackLife/TPLink-hs100-PHP-REST-API#2]
Looks like TPLink have made some changes to the API for authentication with the new app update - they've implemented 2FA but even when this isn't enabled on the account I'm getting "Invalid Credentials" errors when running the API script

```
Fatal error: Uncaught Exception: Invalid credentials in tpLinkApi.php:88
Stack trace:
#0 /tpLinkApi.php(96): TpLink->returnToken()
#1 /smartPlugsLogic.php(43): TpLink->getDeviceList()
```

**Comment by P110** [comment]
Making the request manually in postman gives the response:

```
{
    "error_code": -10306,
    "msg": "Access denied request in blackList"
}
```

**Comment by P110** [comment]
So ... it turns out that 2 things are true:

1. There _is_ a new login API that I reverse-engineered from decompiling the app yesterday, and it's a PITA to use because you need to generate signatures for every request
2. The old API still works
3. My IP has been blacklisted by TP-Link for some reason...

**Comment by P110** [comment]
If they ever turn the old API off & we need to use the new auth API, here are some details, I don't know if any other API endpoints were changed because I didn't get that far before working out my IP was blacklisted.

New login endpoint (POST REQUEST): https://n-wap-gw.tplinkcloud.com/api/v2/account/login

Some Java code I ripped from the app and modified to get working in isolation, generates the signatures & Base-64'd MD5 header:
```java
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.UUID;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.util.Base64;

public class MyClass {
    private static final String COMMA = ",";
    private static final String EMPTY = " ";
    private static final String HMACSHA1 = "HmacSHA1";
    private static final String MD5 = "md5";
    
    public static void main(String args[]) {
        
      String nonce = getNonce();
      String content = "{\"appType\":\"Kasa_Android_Mix\",\"appVersion\":\"3.0.2\",\"cloudPassword\":\"PASSWORD\",\"cloudUserName\":\"EMAIL\",\"platform\":\"Android 11\",\"refreshTokenNeeded\":false,\"terminalMeta\":\"1\",\"terminalName\":\"Google sdk_gphone_x86\",\"terminalUUID\":\"" + getNonce() + "\"}";
      System.out.println(content);
      String contentMD5 = getContentMD5(content);
      System.out.println(contentMD5);
      String signature = getSignature(contentMD5, "9999999999", nonce, "/api/v2/account/login", "314bc6700b3140ca80bc655e527cb062");
      System.out.println(signature);
      System.out.println("Timestamp=9999999999, Nonce=" + nonce + ", AccessKey=e37525375f8845999bcc56d5e6faa76d, Signature=" + signature);
    }

    public static String getContentMD5(String str) {
        byte[] bArr;
        try {
            bArr = MessageDigest.getInstance(MD5).digest(str.getBytes(StandardCharsets.UTF_8));
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            bArr = null;
        }
        return Base64.getEncoder().encodeToString(bArr);
    }
    
    public static String getNonce() {
        return UUID.randomUUID().toString();
    }

    public static String byte2hex(byte[] bArr) {
        StringBuilder sb = new StringBuilder();
        int i = 0;
        while (bArr != null && i < bArr.length) {
            String hexString = Integer.toHexString(bArr[i] & 255);
            if (hexString.length() == 1) {
                sb.append('0');
            }
            sb.append(hexString);
            i++;
        }
        return sb.toString().toLowerCase();
    }
    
    public static String getSignature(String contentMD5, String str2, String str3, String str4, String str5) {
        String toSign = contentMD5 + "\n" + str2 + "\n" + str3 + "\n" + str4;
        try {
            SecretKeySpec secretKeySpec = new SecretKeySpec(str5.getBytes(), HMACSHA1);
            Mac instance = Mac.getInstance(HMACSHA1);
            instance.init(secretKeySpec);
            return byte2hex(instance.doFinal(toSign.getBytes()));
        } catch (InvalidKeyException | NoSuchAlgorithmException e) {
            e.printStackTrace();
            return null;
        }
    }
}
```

The line beginning with "Timestamp=" needs to be placed in an "X-AUTHORIZATION" header and the MD5 hash needs to go in the "Content-MD5" header.

Example response:
```json
{
    "error_code": 0,
    "result": {
        "accountId": "123456",
        "regionCode": "GB",
        "regTime": "2017-06-30 14:38:35",
        "appServerUrl": "https://n-euw1-wap.tplinkcloud.com",
        "riskDetected": 0,
        "errorCode": "0",
        "email": "EMAIL",
        "token": "TOKEN"
    }
}
```
